### ISSUE TITLE
Check for Simulation & Output settings

### ISSUE THREAD

**Issue by alhaas** [dhia-gharsallaoui/watervalues#4]
Hi Dhia, it would be nice if the script could check before launching the Antares simulation if the settings needed for the calculation of water values (e.g. "weekly year by year output", export mc scenarios,...) are set correctly in order to avoid running the simulation and only afterwards checking that it is missing the files.

**Comment by dhia-gharsallaoui** [comment]
Hi Alexandre,

- The information imported from the simulation are the results of the District “**water values district**”. And the creation of the district is done in the scripts `setupWaterValuesSimulation` which impose the output. So no need to touch the others parameters.

`antaresEditObject::createDistrict(
      name = "water values district",
      caption = "water values district",
      comments = "Used for calculate water values",
      apply_filter = "add-all",
      remove_area = append(remove_areas,fictive_area),
      output = TRUE,
      overwrite = TRUE,
      opts = opts
    )`
 

> For your issue, you can investigate it more using the function `get_Reward()` separately.


- In the end of each simulation the script check if the simulation is well done or not by checking the existence of the synthesis year results. And if it’s not the case it will stop the simulations to avoid running useless ones.

**Comment by alhaas** [comment]
Alright, thanks, I will have a look into it!
